// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ODW_MultiLanguageSystem","status":true,"description":"[v1.1.0] - Manage game texts in several languages.","parameters":{"option":"Languages","folder":"languages","fonts":"[]","languages":"[\"{\\\"code\\\":\\\"zh\\\",\\\"label\\\":\\\"Chinese\\\",\\\"folder\\\":\\\"zh\\\",\\\"fontName\\\":\\\"\\\",\\\"fontSize\\\":\\\"0\\\",\\\"files\\\":\\\"[]\\\",\\\"coreTexts\\\":\\\"\\\",\\\"miss\\\":\\\"Miss\\\",\\\"on\\\":\\\"ON\\\",\\\"off\\\":\\\"OFF\\\"}\",\"{\\\"code\\\":\\\"en\\\",\\\"label\\\":\\\"English\\\",\\\"folder\\\":\\\"eng\\\",\\\"fontName\\\":\\\"\\\",\\\"fontSize\\\":\\\"0\\\",\\\"files\\\":\\\"[\\\\\\\"main\\\\\\\",\\\\\\\"characters\\\\\\\",\\\\\\\"START_LOGS\\\\\\\"]\\\",\\\"coreTexts\\\":\\\"\\\",\\\"miss\\\":\\\"Miss\\\",\\\"on\\\":\\\"ON\\\",\\\"off\\\":\\\"OFF\\\"}\"]","useErrorLog":"false"}},
{"name":"Drag_WordWrapping","status":true,"description":"A word wrapping plugin for MZ.\r\nv1.10.0","parameters":{"offset":"15","calcFaceWidth":"true"}}
];
